"""Static batch format_transform overload stubs (generated).

DO NOT EDIT MANUALLY.
Generated by: scripts/generate_chemfile_format_transform_stubs.py
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Literal, overload

from molop.io.codec_types import GraphPolicy

class BatchFormatTransformMixin:
    @overload
    def format_transform(
        self,
        format: Literal["cml"],
        output_dir: str | None = None,
        frameID: int | Literal["all"] | Sequence[int] = -1,
        embed_in_one_file: bool = True,
        n_jobs: int = 1,
        *,
        graph_policy: GraphPolicy = "prefer",
        engine: Literal["rdkit", "openbabel"] = ...,
        **kwargs: Any,
    ) -> dict[str, str | list[str]]:
        """Transform using the `cml` writer overload.

        Args:
            format: Target output format literal for this overload.
            output_dir: Output directory for generated files; defaults to batch behavior when omitted.
            frameID: Frame selector forwarded to per-file rendering.
            embed_in_one_file: Whether selected frames are embedded into one file when supported by the format.
            n_jobs: Parallelism used by batch transform.
            graph_policy: Molecular graph policy used before rendering (for example, `"prefer"`).
            **kwargs: Additional writer options accepted by the implementation.

        Format-specific Args:
            engine: `Literal['rdkit', 'openbabel']` (optional).

        Returns:
            (dict[str, str | list[str]]): Mapping from source path to generated output path(s).

        Source:
            src/molop/io/codecs/_shared/writer_helpers.py:115
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["gjf"],
        output_dir: str | None = None,
        frameID: int | Literal["all"] | Sequence[int] = -1,
        embed_in_one_file: bool = True,
        n_jobs: int = 1,
        *,
        graph_policy: GraphPolicy = "prefer",
        options: str | None = ...,
        route: str | None = ...,
        title_card: str | None = ...,
        suffix: str | None = ...,
        template: str | None = ...,
        use_link1: bool = ...,
        chk: bool | str | None = ...,
        old_chk: bool | str | None = ...,
        **kwargs: Any,
    ) -> dict[str, str | list[str]]:
        """Transform using the `gjf` writer overload.

        Args:
            format: Target output format literal for this overload.
            output_dir: Output directory for generated files; defaults to batch behavior when omitted.
            frameID: Frame selector forwarded to per-file rendering.
            embed_in_one_file: Whether selected frames are embedded into one file when supported by the format.
            n_jobs: Parallelism used by batch transform.
            graph_policy: Molecular graph policy used before rendering (for example, `"prefer"`).
            **kwargs: Additional writer options accepted by the implementation.

        Format-specific Args:
            options: `str | None` (optional).
            route: `str | None` (optional).
            title_card: `str | None` (optional).
            suffix: `str | None` (optional).
            template: `str | None` (optional).
            use_link1: `bool` (optional).
            chk: `bool | str | None` (optional).
            old_chk: `bool | str | None` (optional).

        Returns:
            (dict[str, str | list[str]]): Mapping from source path to generated output path(s).

        Source:
            src/molop/io/logic/qminput_frame_models/GJFFileFrame.py:174
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["orcainp"],
        output_dir: str | None = None,
        frameID: int | Literal["all"] | Sequence[int] = -1,
        embed_in_one_file: bool = True,
        n_jobs: int = 1,
        *,
        graph_policy: GraphPolicy = "prefer",
        keywords: str | None = ...,
        resources_raw: str | None = ...,
        nprocs: int | None = ...,
        maxcore: int | None = ...,
        blocks: str | None = ...,
        use_raw_geometry: bool = ...,
        **kwargs: Any,
    ) -> dict[str, str | list[str]]:
        """Transform using the `orcainp` writer overload.

        Args:
            format: Target output format literal for this overload.
            output_dir: Output directory for generated files; defaults to batch behavior when omitted.
            frameID: Frame selector forwarded to per-file rendering.
            embed_in_one_file: Whether selected frames are embedded into one file when supported by the format.
            n_jobs: Parallelism used by batch transform.
            graph_policy: Molecular graph policy used before rendering (for example, `"prefer"`).
            **kwargs: Additional writer options accepted by the implementation.

        Format-specific Args:
            keywords: `str | None` (optional).
            resources_raw: `str | None` (optional).
            nprocs: `int | None` (optional).
            maxcore: `int | None` (optional).
            blocks: `str | None` (optional).
            use_raw_geometry: `bool` (optional).

        Returns:
            (dict[str, str | list[str]]): Mapping from source path to generated output path(s).

        Source:
            src/molop/io/logic/qminput_frame_models/ORCAInpFileFrame.py:25
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["sdf"],
        output_dir: str | None = None,
        frameID: int | Literal["all"] | Sequence[int] = -1,
        embed_in_one_file: bool = True,
        n_jobs: int = 1,
        *,
        graph_policy: GraphPolicy = "prefer",
        engine: Literal["rdkit", "openbabel"] = ...,
        **kwargs: Any,
    ) -> dict[str, str | list[str]]:
        """Transform using the `sdf` writer overload.

        Args:
            format: Target output format literal for this overload.
            output_dir: Output directory for generated files; defaults to batch behavior when omitted.
            frameID: Frame selector forwarded to per-file rendering.
            embed_in_one_file: Whether selected frames are embedded into one file when supported by the format.
            n_jobs: Parallelism used by batch transform.
            graph_policy: Molecular graph policy used before rendering (for example, `"prefer"`).
            **kwargs: Additional writer options accepted by the implementation.

        Format-specific Args:
            engine: `Literal['rdkit', 'openbabel']` (optional).

        Returns:
            (dict[str, str | list[str]]): Mapping from source path to generated output path(s).

        Source:
            src/molop/io/logic/coords_frame_models/SDFFileFrame.py:18
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["smi"],
        output_dir: str | None = None,
        frameID: int | Literal["all"] | Sequence[int] = -1,
        embed_in_one_file: bool = True,
        n_jobs: int = 1,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> dict[str, str | list[str]]:
        """Transform using the `smi` writer overload.

        Args:
            format: Target output format literal for this overload.
            output_dir: Output directory for generated files; defaults to batch behavior when omitted.
            frameID: Frame selector forwarded to per-file rendering.
            embed_in_one_file: Whether selected frames are embedded into one file when supported by the format.
            n_jobs: Parallelism used by batch transform.
            graph_policy: Molecular graph policy used before rendering (for example, `"prefer"`).
            **kwargs: Additional writer options accepted by the implementation.

        Format-specific Args:
            None.

        Returns:
            (dict[str, str | list[str]]): Mapping from source path to generated output path(s).

        Source:
            src/molop/io/logic/coords_frame_models/SMIFileFrame.py:16
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["xyz"],
        output_dir: str | None = None,
        frameID: int | Literal["all"] | Sequence[int] = -1,
        embed_in_one_file: bool = True,
        n_jobs: int = 1,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> dict[str, str | list[str]]:
        """Transform using the `xyz` writer overload.

        Args:
            format: Target output format literal for this overload.
            output_dir: Output directory for generated files; defaults to batch behavior when omitted.
            frameID: Frame selector forwarded to per-file rendering.
            embed_in_one_file: Whether selected frames are embedded into one file when supported by the format.
            n_jobs: Parallelism used by batch transform.
            graph_policy: Molecular graph policy used before rendering (for example, `"prefer"`).
            **kwargs: Additional writer options accepted by the implementation.

        Format-specific Args:
            None.

        Returns:
            (dict[str, str | list[str]]): Mapping from source path to generated output path(s).

        Source:
            src/molop/io/logic/coords_frame_models/XYZFileFrame.py:20
        """
        ...
    @overload
    def format_transform(
        self,
        format: str,
        output_dir: str | None = None,
        frameID: int | Literal["all"] | Sequence[int] = -1,
        embed_in_one_file: bool = True,
        n_jobs: int = 1,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> dict[str, str | list[str]]:
        """Transform using a format string and format-specific writer options.

        Args:
            format: Target output format literal for this overload.
            output_dir: Output directory for generated files; defaults to batch behavior when omitted.
            frameID: Frame selector forwarded to per-file rendering.
            embed_in_one_file: Whether selected frames are embedded into one file when supported by the format.
            n_jobs: Parallelism used by batch transform.
            graph_policy: Molecular graph policy used before rendering (for example, `"prefer"`).
            **kwargs: Additional writer options accepted by the implementation.

        Format-specific Args by format:
            cml:
                engine: `Literal['rdkit', 'openbabel']` (optional).
            gjf:
                options: `str | None` (optional).
                route: `str | None` (optional).
                title_card: `str | None` (optional).
                suffix: `str | None` (optional).
                template: `str | None` (optional).
                use_link1: `bool` (optional).
                chk: `bool | str | None` (optional).
                old_chk: `bool | str | None` (optional).
            orcainp:
                keywords: `str | None` (optional).
                resources_raw: `str | None` (optional).
                nprocs: `int | None` (optional).
                maxcore: `int | None` (optional).
                blocks: `str | None` (optional).
                use_raw_geometry: `bool` (optional).
            sdf:
                engine: `Literal['rdkit', 'openbabel']` (optional).
            smi:
                None.
            xyz:
                None.

        Returns:
            (dict[str, str | list[str]]): Mapping from source path to generated output path(s).

        Source:
            cml: src/molop/io/codecs/_shared/writer_helpers.py:115
            gjf: src/molop/io/logic/qminput_frame_models/GJFFileFrame.py:174
            orcainp: src/molop/io/logic/qminput_frame_models/ORCAInpFileFrame.py:25
            sdf: src/molop/io/logic/coords_frame_models/SDFFileFrame.py:18
            smi: src/molop/io/logic/coords_frame_models/SMIFileFrame.py:16
            xyz: src/molop/io/logic/coords_frame_models/XYZFileFrame.py:20
        """
        ...
