"""Static typing catalog for MolOP IO (generated).

DO NOT EDIT MANUALLY.
Generated by: scripts/generate_io_typing_catalog.py
"""

from __future__ import annotations

from typing import TypeAlias

from molop.io.logic.coords.frame_models.SDFFileFrame import SDFFileFrameDisk
from molop.io.logic.coords.frame_models.SMIFileFrame import SMIFileFrameDisk
from molop.io.logic.coords.frame_models.XYZFileFrame import XYZFileFrameDisk
from molop.io.logic.coords.models.SDFFile import SDFFileDisk
from molop.io.logic.coords.models.SMIFile import SMIFileDisk
from molop.io.logic.coords.models.XYZFile import XYZFileDisk
from molop.io.logic.gaussian.fchk.output.frame_models.G16FchkFileFrame import G16FchkFileFrameDisk
from molop.io.logic.gaussian.fchk.output.models.G16FchkFile import G16FchkFileDisk
from molop.io.logic.gaussian.input.frame_models.GJFFileFrame import GJFFileFrameDisk
from molop.io.logic.gaussian.input.models.GJFFile import GJFFileDisk
from molop.io.logic.gaussian.log.frame_models.G16LogFileFrame import G16LogFileFrameDisk
from molop.io.logic.gaussian.log.models.G16LogFile import G16LogFileDisk
from molop.io.logic.orca.input.frame_models.ORCAInpFileFrame import ORCAInpFileFrameDisk
from molop.io.logic.orca.input.models.ORCAInpFile import ORCAInpFileDisk
from molop.io.logic.orca.log.frame_models.ORCALogFileFrame import ORCALogFileFrameDisk
from molop.io.logic.orca.log.models.ORCALogFile import ORCALogFileDisk
from molop.io.logic.xtb.output.frame_models.XTBOutputFileFrame import XTBOutputFileFrameDisk
from molop.io.logic.xtb.output.models.XTBOutputFile import XTBOutputFileDisk

FileDiskObj: TypeAlias = (
    G16FchkFileDisk
    | G16LogFileDisk
    | GJFFileDisk
    | ORCAInpFileDisk
    | ORCALogFileDisk
    | SDFFileDisk
    | SMIFileDisk
    | XTBOutputFileDisk
    | XYZFileDisk
)
FrameDiskObj: TypeAlias = (
    G16FchkFileFrameDisk
    | G16LogFileFrameDisk
    | GJFFileFrameDisk
    | ORCAInpFileFrameDisk
    | ORCALogFileFrameDisk
    | SDFFileFrameDisk
    | SMIFileFrameDisk
    | XTBOutputFileFrameDisk
    | XYZFileFrameDisk
)
