

pages:
  tags:
    - pages-builder
  stage: deploy
  before_script:
    - pip install mkdocs
    - pip install mkdocstrings[python]
  script:
    - dummy
  variables:
    BUILDER: 'mkdocs'
    WORKING_DIR: ''
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

