pages:
  tags:
    - pages-builder
  stage: deploy
  script:
    - pip install mkdocs-material mkdocs-heti-plugin mkdocstrings[python] nbconvert notebook==6.4.12 jupyter_contrib_nbextensions mkdocs-static-i18n
    - jupyter nbconvert --to markdown docs/*/*.ipynb
    - mkdocs build --verbose
  variables:
    BUILDER: 'mkdocs'
    WORKING_DIR: ''
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
