before_script:
  - pip install mkdocs
  - pip install mkdocstrings[python]

pages:
  tags:
    - pages-builder
  stage: deploy
  script:
    - pip install mkdocs
    - pip install mkdocstrings[python]
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
