"""Static Typer CLI stubs for transform overloads (generated).

DO NOT EDIT MANUALLY.
Generated by: scripts/generate_cli_transform_stubs.py
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Literal, overload

import typer

app: typer.Typer

def version_callback(
    value: bool,
) -> None: ...
def main(
    verbose: bool = False,
    quiet: bool = False,
    _version: bool | None = None,
) -> None: ...
def summary(
    pattern: str,
    out: Path | None = None,
    format: str = "csv",
    mode: str = "frame",
    frame: str = "-1",
    parser_detection: str = "auto",
    n_jobs: int = -1,
) -> None: ...
def visualize(
    pattern: str,
    out: Path,
    max_mols: int = 16,
    mols_per_row: int = 4,
    sub_img_width: int = 200,
    sub_img_height: int = 200,
    n_jobs: int = -1,
    parser_detection: str = "auto",
) -> None: ...
@overload
def transform(
    pattern: str,
    to: Literal["cml"],
    output_dir: Path,
    frame: str = "-1",
    embed: bool = True,
    parser_detection: str = "auto",
    n_jobs: int = -1,
    *,
    engine: Literal["rdkit", "openbabel"] = ...,
    **kwargs: Any,
) -> None:
    """Transform files using the `cml` writer.

    Args:
        pattern: File pattern to match.
        to: Target writer format.
        output_dir: Directory to save transformed files.
        frame: Frame selection (for example, `all`, `-1`, `1,2`).
        embed: Whether to embed multiple frames in one file.
        parser_detection: Parser detection mode.
        n_jobs: Number of parallel jobs.

    Format-specific Args:
        engine: `Literal['rdkit', 'openbabel']` (optional).

    Source:
        src/molop/io/codecs/_shared/writer_helpers.py:115
    """
    ...

@overload
def transform(
    pattern: str,
    to: Literal["gjf"],
    output_dir: Path,
    frame: str = "-1",
    embed: bool = True,
    parser_detection: str = "auto",
    n_jobs: int = -1,
    *,
    options: str | None = ...,
    route: str | None = ...,
    title_card: str | None = ...,
    suffix: str | None = ...,
    template: str | None = ...,
    use_link1: bool = ...,
    chk: bool | str | None = ...,
    old_chk: bool | str | None = ...,
    **kwargs: Any,
) -> None:
    """Transform files using the `gjf` writer.

    Args:
        pattern: File pattern to match.
        to: Target writer format.
        output_dir: Directory to save transformed files.
        frame: Frame selection (for example, `all`, `-1`, `1,2`).
        embed: Whether to embed multiple frames in one file.
        parser_detection: Parser detection mode.
        n_jobs: Number of parallel jobs.

    Format-specific Args:
        options: `str | None` (optional).
        route: `str | None` (optional).
        title_card: `str | None` (optional).
        suffix: `str | None` (optional).
        template: `str | None` (optional).
        use_link1: `bool` (optional).
        chk: `bool | str | None` (optional).
        old_chk: `bool | str | None` (optional).

    Source:
        src/molop/io/logic/qminput_frame_models/GJFFileFrame.py:174
    """
    ...

@overload
def transform(
    pattern: str,
    to: Literal["orcainp"],
    output_dir: Path,
    frame: str = "-1",
    embed: bool = True,
    parser_detection: str = "auto",
    n_jobs: int = -1,
    *,
    keywords: str | None = ...,
    resources_raw: str | None = ...,
    nprocs: int | None = ...,
    maxcore: int | None = ...,
    blocks: str | None = ...,
    use_raw_geometry: bool = ...,
    **kwargs: Any,
) -> None:
    """Transform files using the `orcainp` writer.

    Args:
        pattern: File pattern to match.
        to: Target writer format.
        output_dir: Directory to save transformed files.
        frame: Frame selection (for example, `all`, `-1`, `1,2`).
        embed: Whether to embed multiple frames in one file.
        parser_detection: Parser detection mode.
        n_jobs: Number of parallel jobs.

    Format-specific Args:
        keywords: `str | None` (optional).
        resources_raw: `str | None` (optional).
        nprocs: `int | None` (optional).
        maxcore: `int | None` (optional).
        blocks: `str | None` (optional).
        use_raw_geometry: `bool` (optional).

    Source:
        src/molop/io/logic/qminput_frame_models/ORCAInpFileFrame.py:25
    """
    ...

@overload
def transform(
    pattern: str,
    to: Literal["sdf"],
    output_dir: Path,
    frame: str = "-1",
    embed: bool = True,
    parser_detection: str = "auto",
    n_jobs: int = -1,
    *,
    engine: Literal["rdkit", "openbabel"] = ...,
    **kwargs: Any,
) -> None:
    """Transform files using the `sdf` writer.

    Args:
        pattern: File pattern to match.
        to: Target writer format.
        output_dir: Directory to save transformed files.
        frame: Frame selection (for example, `all`, `-1`, `1,2`).
        embed: Whether to embed multiple frames in one file.
        parser_detection: Parser detection mode.
        n_jobs: Number of parallel jobs.

    Format-specific Args:
        engine: `Literal['rdkit', 'openbabel']` (optional).

    Source:
        src/molop/io/logic/coords_frame_models/SDFFileFrame.py:18
    """
    ...

@overload
def transform(
    pattern: str,
    to: Literal["smi"],
    output_dir: Path,
    frame: str = "-1",
    embed: bool = True,
    parser_detection: str = "auto",
    n_jobs: int = -1,
    **kwargs: Any,
) -> None:
    """Transform files using the `smi` writer.

    Args:
        pattern: File pattern to match.
        to: Target writer format.
        output_dir: Directory to save transformed files.
        frame: Frame selection (for example, `all`, `-1`, `1,2`).
        embed: Whether to embed multiple frames in one file.
        parser_detection: Parser detection mode.
        n_jobs: Number of parallel jobs.

    Format-specific Args:
        None.

    Source:
        src/molop/io/logic/coords_frame_models/SMIFileFrame.py:16
    """
    ...

@overload
def transform(
    pattern: str,
    to: Literal["xyz"],
    output_dir: Path,
    frame: str = "-1",
    embed: bool = True,
    parser_detection: str = "auto",
    n_jobs: int = -1,
    **kwargs: Any,
) -> None:
    """Transform files using the `xyz` writer.

    Args:
        pattern: File pattern to match.
        to: Target writer format.
        output_dir: Directory to save transformed files.
        frame: Frame selection (for example, `all`, `-1`, `1,2`).
        embed: Whether to embed multiple frames in one file.
        parser_detection: Parser detection mode.
        n_jobs: Number of parallel jobs.

    Format-specific Args:
        None.

    Source:
        src/molop/io/logic/coords_frame_models/XYZFileFrame.py:20
    """
    ...

@overload
def transform(
    pattern: str,
    to: str,
    output_dir: Path,
    frame: str = "-1",
    embed: bool = True,
    parser_detection: str = "auto",
    n_jobs: int = -1,
    **kwargs: Any,
) -> None:
    """Transform files using a dynamic writer format.

    Args:
        pattern: File pattern to match.
        to: Target writer format.
        output_dir: Directory to save transformed files.
        frame: Frame selection (for example, `all`, `-1`, `1,2`).
        embed: Whether to embed multiple frames in one file.
        parser_detection: Parser detection mode.
        n_jobs: Number of parallel jobs.

    Format-specific Args:
        cml:
            engine: `Literal['rdkit', 'openbabel']` (optional).
        gjf:
            options: `str | None` (optional).
            route: `str | None` (optional).
            title_card: `str | None` (optional).
            suffix: `str | None` (optional).
            template: `str | None` (optional).
            use_link1: `bool` (optional).
            chk: `bool | str | None` (optional).
            old_chk: `bool | str | None` (optional).
        orcainp:
            keywords: `str | None` (optional).
            resources_raw: `str | None` (optional).
            nprocs: `int | None` (optional).
            maxcore: `int | None` (optional).
            blocks: `str | None` (optional).
            use_raw_geometry: `bool` (optional).
        sdf:
            engine: `Literal['rdkit', 'openbabel']` (optional).
        smi:
            None.
        xyz:
            None.

    Source:
        cml: src/molop/io/codecs/_shared/writer_helpers.py:115
        gjf: src/molop/io/logic/qminput_frame_models/GJFFileFrame.py:174
        orcainp: src/molop/io/logic/qminput_frame_models/ORCAInpFileFrame.py:25
        sdf: src/molop/io/logic/coords_frame_models/SDFFileFrame.py:18
        smi: src/molop/io/logic/coords_frame_models/SMIFileFrame.py:16
        xyz: src/molop/io/logic/coords_frame_models/XYZFileFrame.py:20
    """
    ...

def filter_by_codec(
    pattern: str,
    codec_id: str,
    negate: bool = False,
    on_missing: str = "drop",
    out_format: str = "text",
    parser_detection: str = "auto",
    n_jobs: int = -1,
) -> None: ...
def sample(
    pattern: str,
    n: int,
    seed: int | None = None,
    out_format: str = "text",
    parser_detection: str = "auto",
    n_jobs: int = -1,
) -> None: ...
def stats(
    pattern: str,
    format: str = "text",
    parser_detection: str = "auto",
    n_jobs: int = -1,
) -> None: ...
def groupby(
    pattern: str,
    key: str = "detected_format_id",
    format: str = "json",
    parser_detection: str = "auto",
    n_jobs: int = -1,
) -> None: ...
