name: MolOP wheel building
run-name: ${{ gitea.actor }} is Running 🚀
on:
  push:
    branches: [main]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: https://gitea.com/actions/checkout@v3
      - name: set mirror
        run: pip config set global.index-url https://mirrors.zju.edu.cn/pypi/web/simple
      - name: register to gitea
        run: | 
          export OWNER=${{ secrets.OWNER }}
          export PASSWORD=${{ secrets.PASSWORD }}
          echo "[distutils]\nindex-servers = gitea\n\n[gitea]\nrepository = https://gitea.example.com/api/packages/$OWNER/pypi\nusername = $OWNER\npassword = $PASSWORD" > ~/.pypric
      - run: cat ~/.pypric
      - name: Deploy latest
        run: |
          pip install twine
          python setup.py bdist_wheel
          python3 -m twine upload --repository gitea dist/*
      - run: echo "🍏 This job's status is ${{ job.status }}."
