name: MolOP wheel building
run-name: ${{ gitea.actor }} is Running 🚀
on:
  push:
    branches: [main]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: https://gitea.com/actions/checkout@v3
      - name: set mirror
        run: pip config set global.index-url https://mirrors.zju.edu.cn/pypi/web/simple
      - name: register to gitea
        run: | 
          cat > ~/.pypirc << EOF
          [distutils]
          index-servers = gitea

          [gitea]
          repository = http://10.72.201.58:13000/api/packages/${{ secrets.OWNER }}/pypi
          username = ${{ secrets.OWNER }}
          password = ${{ secrets.PASSWORD }}
          EOF
      - run: cat ~/.pypirc
      - name: Deploy latest
        run: |
          pip install twine
          python setup.py bdist_wheel
          python -m twine upload --repository gitea dist/*
      - run: echo "🍏 This job's status is ${{ job.status }}."
