"""
Author: TMJ
Date: 2025-07-31 20:27:42
LastEditors: TMJ
LastEditTime: 2026-02-05 19:54:13
Description: 请填写简介
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from typing import TYPE_CHECKING, Protocol, cast

import numpy as np
from pint.facets.plain import PlainQuantity
from pydantic import Field

from molop.io.base_models.ChemFile import BaseCalcFile
from molop.io.base_models.Mixins import DiskStorageMixin, MemoryStorageMixin
from molop.io.frame_selection import FrameSelector, normalize_frame_selector
from molop.io.logic.gaussian.input.GaussianLink0 import render_gaussian_link0_shared_memory_line
from molop.io.logic.gaussian.input.GaussianRoute import GaussianRouteSemanticFieldsMixin
from molop.io.logic.gaussian.log.frame_models.G16LogFileFrame import (
    G16LogFileFrameDisk,
    G16LogFileFrameMemory,
)


if TYPE_CHECKING:
    from molop.io.codec_registry import Registry


class G16LogFileMixin(GaussianRouteSemanticFieldsMixin):
    standard_orientation_transformation_matrix: np.ndarray | None = Field(
        default=None,
        description="Transformation matrix to standard orientation, unit is `angstrom`",
        title="Transformation matrix to standard orientation",
        repr=False,
    )

    @staticmethod
    def _electron_counts(
        atoms: Sequence[int] | None,
        charge: int,
        multiplicity: int,
    ) -> tuple[int | None, int | None]:
        if not atoms:
            return None, None
        total_electrons = int(sum(int(atom) for atom in atoms) - charge)
        spin_excess = multiplicity - 1
        if total_electrons < 0 or (total_electrons + spin_excess) % 2 != 0:
            return None, None
        alpha = (total_electrons + spin_excess) // 2
        beta = total_electrons - alpha
        if alpha < 0 or beta < 0:
            return None, None
        return alpha, beta

    @staticmethod
    def _render_fakeg_symbolic_z_matrix(
        frame: G16LogFileFrameMemory | G16LogFileFrameDisk,
    ) -> list[str]:
        lines = [
            " Symbolic Z-matrix:",
            f" Charge = {frame.charge:2d} Multiplicity = {frame.multiplicity}",
        ]
        coords = frame.coords.m if hasattr(frame.coords, "m") else frame.coords
        for symbol, xyz in zip(frame.atom_symbols, coords, strict=False):
            lines.append(
                f" {symbol:<2}{float(xyz[0]):21.5f}{float(xyz[1]):11.5f}{float(xyz[2]):11.5f}"
            )
        return lines

    def _render_fakeg_header(self) -> str:
        typed_self = cast(_HasG16RenderedFrames, self)
        first_frame = typed_self.frames[0] if typed_self.frames else None
        version = typed_self.qm_software_version or "Gaussian fakeG generated by MolOP"
        version_lines = version.splitlines()
        if version and not any("gaussian" in line.lower() for line in version_lines):
            version_lines.insert(0, f"Gaussian 16:  {version}")
        lines = [
            " ******************************************",
            *version_lines,
            " ******************************************",
        ]

        if typed_self.options:
            lines.extend(line for line in typed_self.options.splitlines() if line.strip())
            if cpu_line := render_gaussian_link0_shared_memory_line(typed_self.options):
                lines.append(cpu_line)

        lines.extend(
            [
                " ------------------------------------",
                typed_self.keywords if typed_self.keywords else " #p fakeg",
                " ------------------------------------",
            ]
        )
        if typed_self.title_card:
            lines.extend(
                [
                    " ------------------",
                    typed_self.title_card,
                    " ------------------",
                ]
            )
        if first_frame is not None:
            lines.extend(self._render_fakeg_symbolic_z_matrix(first_frame))
        lines.extend(
            [
                "",
                "",
                "GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad",
                "GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def _render_fakeg_footer() -> str:
        return ""

    @staticmethod
    def _render_fakeg_termination() -> str:
        return " Normal termination of Gaussian"

    @staticmethod
    def _strip_fakeg_runtime_lines(rendered: str) -> str:
        lines = [
            line
            for line in rendered.splitlines()
            if not line.startswith(("Job cpu time:", "Elapsed time:"))
        ]
        return "\n".join(lines).strip()

    @staticmethod
    def _format_fakeg_convergence_line(
        label: str,
        value: PlainQuantity | float,
        threshold: PlainQuantity | float | None,
        converged: bool | None,
    ) -> str:
        value_float = float(value.magnitude) if isinstance(value, PlainQuantity) else float(value)
        threshold_float = None
        if threshold is not None:
            threshold_float = (
                float(threshold.magnitude)
                if isinstance(threshold, PlainQuantity)
                else float(threshold)
            )
        if threshold_float is None or not math.isfinite(threshold_float):
            threshold_str = " " * 13
        else:
            threshold_str = f"{threshold_float:13.6f}"
        state = "YES" if converged is True else "NO"
        return f" {label:<20}{value_float:13.6f}{threshold_str}     {state}"

    @classmethod
    def _render_fakeg_optimization_summary(
        cls,
        geometry_optimization_status: object | None,
        *,
        step_number: int,
    ) -> str:
        if geometry_optimization_status is None or step_number <= 0:
            return ""
        opt = cast(_HasFakeGOptimizationStatus, geometry_optimization_status)
        lines = [
            " GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad",
            f" Step number{step_number:4d}",
            "         Item               Value     Threshold  Converged?",
        ]
        for label, value, threshold, converged in (
            (
                "Maximum Force",
                opt.max_force,
                opt.max_force_threshold,
                opt.max_force_converged,
            ),
            (
                "RMS     Force",
                opt.rms_force,
                opt.rms_force_threshold,
                opt.rms_force_converged,
            ),
            (
                "Maximum Displacement",
                opt.max_displacement,
                opt.max_displacement_threshold,
                opt.max_displacement_converged,
            ),
            (
                "RMS     Displacement",
                opt.rms_displacement,
                opt.rms_displacement_threshold,
                opt.rms_displacement_converged,
            ),
        ):
            if value is not None:
                lines.append(cls._format_fakeg_convergence_line(label, value, threshold, converged))
        lines.append(" GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad")
        return "\n".join(lines)

    @classmethod
    def _render_fakeg_multiframe_file(
        cls,
        frames: Sequence[G16LogFileFrameMemory | G16LogFileFrameDisk],
    ) -> str:
        optimization_frames = [
            frame
            for frame in frames
            if getattr(frame, "geometry_optimization_status", None) is not None
            and getattr(getattr(frame, "energies", None), "total_energy", None) is not None
            and getattr(frame, "vibrations", None) is None
        ]
        frequency_frame = next(
            (frame for frame in reversed(frames) if getattr(frame, "vibrations", None) is not None),
            None,
        )

        sections: list[str] = []
        if optimization_frames:
            for step_number, frame in enumerate(optimization_frames, start=1):
                rendered_frame = cls._strip_fakeg_runtime_lines(frame.render_fakeg())
                optimization_parts = [rendered_frame]
                if optimization_summary := cls._render_fakeg_optimization_summary(
                    getattr(frame, "geometry_optimization_status", None),
                    step_number=step_number,
                ):
                    optimization_parts.append(optimization_summary)
                sections.append("\n\n".join(part for part in optimization_parts if part))
            sections.append(cls._render_fakeg_termination())

        if frequency_frame is not None:
            rendered_frequency_frame = cls._strip_fakeg_runtime_lines(
                frequency_frame.render_fakeg()
            )
            frequency_parts = [rendered_frequency_frame]
            if optimization_summary := cls._render_fakeg_optimization_summary(
                getattr(frequency_frame, "geometry_optimization_status", None),
                step_number=len(optimization_frames) + 1,
            ):
                frequency_parts.append(optimization_summary)
            sections.append("\n\n".join(part for part in frequency_parts if part))
            sections.append(cls._render_fakeg_termination())

        return "\n\n".join(section for section in sections if section)

    def _render_frames_in_one_file(self, frame_ids: Sequence[int], **kwargs) -> str:
        typed_self = cast(_HasG16RenderedFrames, self)
        selected_frames = [frame for frame in typed_self.frames if frame.frame_id in frame_ids]
        if len(selected_frames) > 1:
            body = self._render_fakeg_multiframe_file(selected_frames)
        else:
            body = "\n\n".join(frame.render_fakeg(**kwargs) for frame in selected_frames)
        sections = [self._render_fakeg_header()]
        if body:
            sections.append(body)
        footer = self._render_fakeg_footer()
        if footer:
            sections.append(footer)
        return "\n\n".join(sections)

    def _render_frames(self, frame_ids: Sequence[int], **kwargs) -> list[str]:
        typed_self = cast(_HasG16RenderedFrames, self)
        return [
            frame.render_fakeg(**kwargs)
            for frame in typed_self.frames
            if frame.frame_id in frame_ids
        ]

    def render_fakeg(
        self,
        frame: FrameSelector = "all",
        *,
        embed_in_one_file: bool = True,
        **kwargs,
    ) -> str | list[str]:
        typed_self = cast(_HasG16RenderedFrames, self)
        frame_ids = normalize_frame_selector(
            frame,
            len(typed_self.frames),
            parameter_name="frame",
            validate_range=True,
        )
        selected_frames = [typed_self.frames[frame_id] for frame_id in frame_ids]

        if embed_in_one_file:
            frame_ids = [frame.frame_id for frame in selected_frames]
            return self._render_frames_in_one_file(frame_ids, **kwargs)
        return self._render_frames([frame.frame_id for frame in selected_frames], **kwargs)


class G16LogFileMemory(
    MemoryStorageMixin, G16LogFileMixin, BaseCalcFile[G16LogFileFrameMemory]
): ...


class G16LogFileDisk(DiskStorageMixin, G16LogFileMixin, BaseCalcFile[G16LogFileFrameDisk]): ...


def register(registry: Registry) -> None:
    """Register fakeG as a file-only writer codec."""

    from typing import cast

    from molop.io.codecs._shared.writer_helpers import (
        FileRendererWriter,
        StructureLevel,
        WriterCodec,
    )

    priority = 100

    @registry.writer_factory(
        format_id="fakeg",
        required_level=StructureLevel.COORDS,
        domain="file",
        default_graph_policy="coords",
        priority=priority,
    )
    def _factory() -> WriterCodec:
        return cast(
            WriterCodec,
            FileRendererWriter(
                format_id="fakeg",
                required_level=StructureLevel.COORDS,
                file_cls=G16LogFileDisk,
                frame_cls=G16LogFileFrameDisk,
                priority=priority,
            ),
        )


class _HasG16RenderedFrames(Protocol):
    charge: int
    multiplicity: int
    qm_software_version: str
    options: str
    keywords: str
    title_card: str

    @property
    def frames(self) -> list[G16LogFileFrameMemory | G16LogFileFrameDisk]: ...

    def __getitem__(
        self, frame: Sequence[int] | int | slice
    ) -> (
        G16LogFileFrameMemory
        | G16LogFileFrameDisk
        | list[G16LogFileFrameMemory | G16LogFileFrameDisk]
    ): ...


class _HasG16FileMetadata(Protocol):
    charge: int
    multiplicity: int


class _HasFakeGOptimizationStatus(Protocol):
    max_force: PlainQuantity | float | None
    max_force_threshold: PlainQuantity | float | None
    max_force_converged: bool | None
    rms_force: PlainQuantity | float | None
    rms_force_threshold: PlainQuantity | float | None
    rms_force_converged: bool | None
    max_displacement: PlainQuantity | float | None
    max_displacement_threshold: PlainQuantity | float | None
    max_displacement_converged: bool | None
    rms_displacement: PlainQuantity | float | None
    rms_displacement_threshold: PlainQuantity | float | None
    rms_displacement_converged: bool | None
