"""
Author: TMJ
Date: 2025-07-31 20:27:42
LastEditors: TMJ
LastEditTime: 2026-02-05 19:54:13
Description: 请填写简介
"""

import math
from collections.abc import Sequence
from typing import Literal, Protocol, cast

import numpy as np
from pydantic import Field, model_validator
from typing_extensions import Self

from molop.io.base_models.ChemFile import BaseCalcFile
from molop.io.base_models.Mixins import DiskStorageMixin, MemoryStorageMixin
from molop.io.logic.gaussian_route_models import (
    GaussianRouteSemantic,
    parse_gaussian_route_semantic,
)
from molop.io.logic.QM_frame_models.G16LogFileFrame import (
    G16LogFileFrameDisk,
    G16LogFileFrameMemory,
)
from molop.io.patterns.G16Patterns import (
    SEMI_EMPIRICAL_METHODS,
)


class G16LogFileMixin:
    qm_software: str = Field(default="Gaussian")
    options: str = Field(default="", description="options comment")
    title_card: str = Field(default="", description="title card")
    job_type: str = Field(default="", description="Job type")
    keywords: str = Field(
        default="",
        description="Keywords for the QM parameters",
    )
    method: str = Field(
        default="",
        description="QM method used to perform the calculation. e.g. DFT or GFN2-xTB",
    )
    basis_set: str = Field(
        default="",
        description="Basis set used in the QM calculation, only for DFT calculations",
    )
    functional: str = Field(
        default="",
        description="Functional used in the QM calculation, only for DFT calculations",
    )

    standard_orientation_transformation_matrix: np.ndarray | None = Field(
        default=None,
        description="Transformation matrix to standard orientation, unit is `angstrom`",
        title="Transformation matrix to standard orientation",
        repr=False,
    )

    @model_validator(mode="after")
    def _validate_metadata(self) -> Self:
        semantic_route = self.semantic_route
        if self.basis_set.lower() == "genecp":
            self.basis_set = "pseudopotential"
        elif not self.basis_set and semantic_route.model_chemistry.basis_set is not None:
            self.basis_set = semantic_route.model_chemistry.basis_set

        if not self.functional and semantic_route.model_chemistry.functional is not None:
            self.functional = semantic_route.model_chemistry.functional

        if any(semi in self.keywords.lower() for semi in SEMI_EMPIRICAL_METHODS):
            self.method = "SEMI-EMPIRICAL"
        else:
            if not self.method and semantic_route.model_chemistry.method_family is not None:
                self.method = semantic_route.model_chemistry.method_family
            if self.functional.lower().endswith("hf"):
                self.method = "HF"
            if self.functional.lower().endswith("fc"):
                self.method = "FC"
            else:
                self.method = "DFT"
        if semantic_route.empirical_dispersion:
            self.functional = f"{self.functional}-{semantic_route.empirical_dispersion.upper()}"
        return self

    @property
    def dieze_tag(self) -> str | None:
        return self.semantic_route.dieze_tag

    @property
    def semantic_route(self) -> GaussianRouteSemantic:
        return parse_gaussian_route_semantic(self.keywords)

    @staticmethod
    def _electron_counts(
        atoms: Sequence[int] | None,
        charge: int,
        multiplicity: int,
    ) -> tuple[int | None, int | None]:
        if not atoms:
            return None, None
        total_electrons = int(sum(int(atom) for atom in atoms) - charge)
        spin_excess = multiplicity - 1
        if total_electrons < 0 or (total_electrons + spin_excess) % 2 != 0:
            return None, None
        alpha = (total_electrons + spin_excess) // 2
        beta = total_electrons - alpha
        if alpha < 0 or beta < 0:
            return None, None
        return alpha, beta

    @staticmethod
    def _render_fakeg_symbolic_z_matrix(
        frame: "G16LogFileFrameMemory | G16LogFileFrameDisk",
    ) -> list[str]:
        lines = [
            " Symbolic Z-matrix:",
            f" Charge = {frame.charge:2d} Multiplicity = {frame.multiplicity}",
        ]
        coords = frame.coords.m if hasattr(frame.coords, "m") else frame.coords
        for symbol, xyz in zip(frame.atom_symbols, coords, strict=False):
            lines.append(
                f" {symbol:<2}{float(xyz[0]):21.5f}{float(xyz[1]):11.5f}{float(xyz[2]):11.5f}"
            )
        return lines

    def _render_fakeg_header(self) -> str:
        typed_self = cast(_HasG16RenderedFrames, self)
        first_frame = typed_self.frames[0] if typed_self.frames else None
        version_lines = (
            typed_self.qm_software_version or "Gaussian fakeG generated by MolOP"
        ).splitlines()
        lines = [
            " ******************************************",
            *version_lines,
            " ******************************************",
        ]

        if typed_self.options:
            lines.extend(line for line in typed_self.options.splitlines() if line.strip())
            if "%nprocshared=" in typed_self.options.lower():
                for option_line in typed_self.options.splitlines():
                    stripped = option_line.strip()
                    if stripped.lower().startswith("%nprocshared="):
                        nproc = stripped.split("=", 1)[1].strip()
                        lines.append(
                            f" Will use up to {int(nproc):4d} processors via shared memory."
                            if nproc.isdigit()
                            else " Will use up to shared-memory processors."
                        )
                        break

        lines.extend(
            [
                " ------------------------------------",
                typed_self.keywords if typed_self.keywords else " #p fakeg",
                " ------------------------------------",
            ]
        )
        if typed_self.title_card:
            lines.extend(
                [
                    " ------------------",
                    typed_self.title_card,
                    " ------------------",
                ]
            )
        if first_frame is not None:
            lines.extend(self._render_fakeg_symbolic_z_matrix(first_frame))
        lines.extend(
            [
                "",
                "",
                "GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad",
                "GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad",
            ]
        )
        return "\n".join(lines)

    @staticmethod
    def _render_fakeg_footer() -> str:
        return ""

    @staticmethod
    def _render_fakeg_termination() -> str:
        return " Normal termination of Gaussian"

    @staticmethod
    def _strip_fakeg_runtime_lines(rendered: str) -> str:
        lines = [
            line
            for line in rendered.splitlines()
            if not line.startswith(("Job cpu time:", "Elapsed time:"))
        ]
        return "\n".join(lines).strip()

    @staticmethod
    def _format_fakeg_convergence_line(
        label: str,
        value: float,
        threshold: float | None,
        converged: bool | None,
    ) -> str:
        if threshold is None or not math.isfinite(threshold):
            threshold_str = " " * 13
        else:
            threshold_str = f"{threshold:13.6f}"
        state = "YES" if converged is True else "NO"
        return f" {label:<20}{value:13.6f}{threshold_str}     {state}"

    @classmethod
    def _render_fakeg_optimization_summary(
        cls,
        geometry_optimization_status: object | None,
        *,
        step_number: int,
    ) -> str:
        if geometry_optimization_status is None or step_number <= 0:
            return ""
        opt = cast(_HasFakeGOptimizationStatus, geometry_optimization_status)
        lines = [
            " GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad",
            f" Step number{step_number:4d}",
            "         Item               Value     Threshold  Converged?",
            cls._format_fakeg_convergence_line(
                "Maximum Force",
                float(opt.max_force),
                opt.max_force_threshold,
                opt.max_force_converged,
            ),
            cls._format_fakeg_convergence_line(
                "RMS     Force",
                float(opt.rms_force),
                opt.rms_force_threshold,
                opt.rms_force_converged,
            ),
            cls._format_fakeg_convergence_line(
                "Maximum Displacement",
                float(opt.max_displacement),
                opt.max_displacement_threshold,
                opt.max_displacement_converged,
            ),
            cls._format_fakeg_convergence_line(
                "RMS     Displacement",
                float(opt.rms_displacement),
                opt.rms_displacement_threshold,
                opt.rms_displacement_converged,
            ),
            " GradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGradGrad",
        ]
        return "\n".join(lines)

    @classmethod
    def _render_fakeg_multiframe_file(
        cls,
        frames: Sequence["G16LogFileFrameMemory | G16LogFileFrameDisk"],
    ) -> str:
        optimization_frames = [
            frame
            for frame in frames
            if getattr(frame, "geometry_optimization_status", None) is not None
            and getattr(getattr(frame, "energies", None), "total_energy", None) is not None
            and getattr(frame, "vibrations", None) is None
        ]
        frequency_frame = next(
            (frame for frame in reversed(frames) if getattr(frame, "vibrations", None) is not None),
            None,
        )

        sections: list[str] = []
        if optimization_frames:
            for step_number, frame in enumerate(optimization_frames, start=1):
                rendered_frame = cls._strip_fakeg_runtime_lines(frame.render_fakeg())
                optimization_parts = [rendered_frame]
                if optimization_summary := cls._render_fakeg_optimization_summary(
                    getattr(frame, "geometry_optimization_status", None),
                    step_number=step_number,
                ):
                    optimization_parts.append(optimization_summary)
                sections.append("\n\n".join(part for part in optimization_parts if part))
            sections.append(cls._render_fakeg_termination())

        if frequency_frame is not None:
            rendered_frequency_frame = cls._strip_fakeg_runtime_lines(
                frequency_frame.render_fakeg()
            )
            frequency_parts = [rendered_frequency_frame]
            if optimization_summary := cls._render_fakeg_optimization_summary(
                getattr(frequency_frame, "geometry_optimization_status", None),
                step_number=len(optimization_frames) + 1,
            ):
                frequency_parts.append(optimization_summary)
            sections.append("\n\n".join(part for part in frequency_parts if part))
            sections.append(cls._render_fakeg_termination())

        return "\n\n".join(section for section in sections if section)

    def render_fakeg(
        self,
        frameID: Sequence[int] | int | Literal["all"] | slice = "all",
        *,
        embed_in_one_file: bool = True,
        **kwargs,
    ) -> str | list[str]:
        typed_self = cast(_HasG16RenderedFrames, self)
        if frameID == "all":
            selected_frames = list(typed_self.frames)
        else:
            selected = typed_self[frameID]
            selected_frames = selected if isinstance(selected, list) else [selected]

        rendered_frames = [frame.render_fakeg(**kwargs) for frame in selected_frames]
        if embed_in_one_file:
            if len(selected_frames) > 1:
                body = self._render_fakeg_multiframe_file(selected_frames)
            else:
                body = "\n\n".join(frame for frame in rendered_frames if frame)
            sections = [self._render_fakeg_header()]
            if body:
                sections.append(body)
            footer = self._render_fakeg_footer()
            if footer:
                sections.append(footer)
            return "\n\n".join(sections)
        return rendered_frames


class G16LogFileMemory(
    MemoryStorageMixin, G16LogFileMixin, BaseCalcFile[G16LogFileFrameMemory]
): ...


class G16LogFileDisk(DiskStorageMixin, G16LogFileMixin, BaseCalcFile[G16LogFileFrameDisk]): ...


class _HasG16RenderedFrames(Protocol):
    charge: int
    multiplicity: int
    qm_software_version: str
    options: str
    keywords: str
    title_card: str

    @property
    def frames(self) -> list[G16LogFileFrameMemory | G16LogFileFrameDisk]: ...

    def __getitem__(
        self, frameID: Sequence[int] | int | slice
    ) -> (
        G16LogFileFrameMemory
        | G16LogFileFrameDisk
        | list[G16LogFileFrameMemory | G16LogFileFrameDisk]
    ): ...


class _HasG16FileMetadata(Protocol):
    charge: int
    multiplicity: int


class _HasFakeGOptimizationStatus(Protocol):
    max_force: float
    max_force_threshold: float | None
    max_force_converged: bool | None
    rms_force: float
    rms_force_threshold: float | None
    rms_force_converged: bool | None
    max_displacement: float
    max_displacement_threshold: float | None
    max_displacement_converged: bool | None
    rms_displacement: float
    rms_displacement_threshold: float | None
    rms_displacement_converged: bool | None
