name: Docs Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --frozen --group docs

      - name: Execute documentation notebooks
        run: |
          uv run --frozen --group docs jupyter nbconvert \
            --to notebook \
            --execute \
            --inplace \
            --ExecutePreprocessor.timeout=120 \
            --ExecutePreprocessor.kernel_name=python3 \
            docs/zh/examples/*.ipynb docs/en/examples/*.ipynb
          rm -f summary.csv docs/zh/examples/summary.csv docs/en/examples/summary.csv

      - name: Build docs
        env:
          NO_MKDOCS_2_WARNING: "1"
        run: uv run --frozen --group docs mkdocs build --strict -f mkdocs.yml
