"""Static chemfile format_transform overload stubs (generated).

DO NOT EDIT MANUALLY.
Generated by: scripts/generate_chemfile_format_transform_stubs.py
"""

from __future__ import annotations

import os
from collections.abc import Sequence
from typing import Any, Literal, overload

from molop.io.codec_types import GraphPolicy
from molop.io.logic.qminput_frame_models.GJFFileFrame import (
    GJFGICSection,
    GJFLink0Commands,
    GJFModRedundantSection,
    GJFMoleculeSpecifications,
    GJFRouteSection,
    GJFTitleCard,
    GJFUnknownSection,
)

class FrameFormatTransformMixin:
    @overload
    def format_transform(
        self,
        format: Literal["cml"],
        file_path: os.PathLike | str | None = None,
        *,
        graph_policy: GraphPolicy = "prefer",
        engine: Literal["rdkit", "openbabel"] = ...,
        **kwargs: Any,
    ) -> str:
        """Transform using the `cml` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        file_path :
            Optional output path. If provided, the rendered text is also written to a format-derived file.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the selected structure as CML text.

        Format-specific parameters
        --------------------------
            engine : Literal['rdkit', 'openbabel']
                Format-specific writer argument (optional).

        Render the selected structure as CML text.

        Returns
        -------
        str
            Rendered text for the selected frame.

        Source
        ------
        src/molop/io/codecs/cml_codec.py:78
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["gjf"],
        file_path: os.PathLike | str | None = None,
        *,
        graph_policy: GraphPolicy = "prefer",
        link0_commands: str | GJFLink0Commands | dict[str, str | None] | None = ...,
        route_section: str | GJFRouteSection | None = ...,
        title_card: str | GJFTitleCard | None = ...,
        molecule_specifications: str | GJFMoleculeSpecifications | None = ...,
        additional_sections: str | None = ...,
        parsed_additional_sections: list[GJFGICSection | GJFModRedundantSection | GJFUnknownSection]
        | None = ...,
        chk: str | bool | None = ...,
        old_chk: bool | str | None = ...,
        coords_type: Literal["cartesian", "internal", "auto"] = ...,
        add_gjf_connectivity: bool = ...,
        **kwargs: Any,
    ) -> str:
        """Transform using the `gjf` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        file_path :
            Optional output path. If provided, the rendered text is also written to a format-derived file.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the current GJF frame as Gaussian input text.

        Format-specific parameters
        --------------------------
            link0_commands : str | GJFLink0Commands | dict[str, str | None] | None
                Format-specific writer argument (optional).
            route_section : str | GJFRouteSection | None
                Format-specific writer argument (optional).
            title_card : str | GJFTitleCard | None
                Format-specific writer argument (optional).
            molecule_specifications : str | GJFMoleculeSpecifications | None
                Format-specific writer argument (optional).
            additional_sections : str | None
                Format-specific writer argument (optional).
            parsed_additional_sections : list[GJFGICSection | GJFModRedundantSection | GJFUnknownSection] | None
                Format-specific writer argument (optional).
            chk : str | bool | None
                Format-specific writer argument (optional).
            old_chk : bool | str | None
                Format-specific writer argument (optional).
            coords_type : Literal['cartesian', 'internal', 'auto']
                Format-specific writer argument (optional).
            add_gjf_connectivity : bool
                Format-specific writer argument (optional).

        Render the current GJF frame as Gaussian input text.

        The method assembles the output in standard Gaussian input order:
        1. Link0 commands
        2. Route section
        3. Title card
        4. Molecule specifications
        5. Additional sections

        Callers may temporarily override any of these parts for a single render
        without mutating the instance first. Any argument left as ``None`` falls
        back to the corresponding attribute on ``self``.

        Parameters
        ----------
        link0_commands : str | GJFLink0Commands | dict[str, str | None] | None, optional
            Link0 content, i.e. the resource and job-control directives at the
            beginning of the file such as ``%mem``, ``%nprocshared``, and
            ``%chk``.

            Actual behavior:
            - ``str``: parsed as Link0 syntax into ``GJFLink0Commands``;
            - ``dict``: converted into a Link0 keyword list;
            - ``GJFLink0Commands``: used directly;
            - ``None``: falls back to ``self.link0_commands``.

        route_section : str | GJFRouteSection | None, optional
            Gaussian route section, i.e. the keyword line beginning with ``#``,
            for example ``#p b3lyp/6-31g(d) opt freq``.

            Actual behavior:
            - ``str``: converted to ``GJFRouteSection`` and normalized there;
            - ``GJFRouteSection``: used directly;
            - ``None``: falls back to ``self.route_section``.

        title_card : str | GJFTitleCard | None, optional
            Gaussian title section.

            Actual behavior:
            - ``str``: converted to ``GJFTitleCard``;
            - ``GJFTitleCard``: used directly;
            - ``None``: falls back to ``self.title_card``;
            - if the final title is empty, it falls back to ``self.pure_filename``
              or, if unavailable, ``"title"``.

        molecule_specifications : str | GJFMoleculeSpecifications | None, optional
            Molecule specification block, i.e. the charge/multiplicity line plus
            the coordinate block that follows it.

            Actual behavior:
            - ``str``: parsed as Gaussian molecule-block syntax into
              ``GJFMoleculeSpecifications``;
            - ``GJFMoleculeSpecifications``: used directly;
            - ``None``: falls back to ``self.molecule_specifications``.

        additional_sections : str | None, optional
            Raw additional-section text appended after the main molecule block,
            such as GIC, ModRedundant, NBO, or other Gaussian extra-input blocks.

            Actual behavior:
            - whenever this argument is explicitly provided, it has top priority;
            - even an empty string overrides the structured additional-section
              sources.

        parsed_additional_sections : list[...] | None, optional
            Structured additional sections. Each section is rendered via its own
            ``_render()`` and then joined with blank lines.

            Actual behavior:
            - only used when ``additional_sections is None``;
            - when provided, it takes priority over
              ``self.parsed_additional_sections``;
            - sections whose rendered text is blank are skipped.

            Additional-section priority is:
            1. ``additional_sections``
            2. ``parsed_additional_sections``
            3. ``self.parsed_additional_sections``
            4. ``self.additional_sections``
            5. empty string

        chk : str | bool | None, optional
            Whether to append an extra ``%chk`` Link0 keyword for this render.

            Actual behavior:
            - ``None`` / ``False``: do not append anything;
            - ``True``: append ``%chk=<basename>.chk``;
            - ``str``: append ``%chk=<given string>``.

            ``<basename>`` is taken from ``self.pure_filename`` when available,
            otherwise from the final title card. This is an append operation, not
            a replacement, and existing ``%chk`` entries are not deduplicated.

        old_chk : str | bool | None, optional
            Whether to append an extra ``%oldchk`` Link0 keyword for this render,
            typically to reference a previous checkpoint file.

            Actual behavior matches ``chk``:
            - ``None`` / ``False``: do not append anything;
            - ``True``: append ``%oldchk=<basename>.chk``;
            - ``str``: append ``%oldchk=<given string>``.

            This is also an append operation and does not replace or deduplicate
            existing ``%oldchk`` entries.

        coords_type : {"cartesian", "internal", "auto"}, default "auto"
            Controls the preferred output form of the coordinate block.

            Actual behavior in the current implementation:
            - ``"auto"``: preserve the stored representation. Each atom
              specification renders itself according to the structure of its own
              ``coords_part``: Cartesian coordinates, internal coordinates, or
              raw text.
            - ``"cartesian"``: require the molecule block to be rendered in
              Cartesian coordinates.
              - If all atoms in a fragment already store Cartesian coordinates,
                they are rendered directly in their current order.
              - If a fragment stores internal coordinates, the fragment is first
                converted through ``frag.coords()`` and then reconstructed as
                Cartesian atom lines.
              - If the fragment contains dummy atoms or ghost atoms, the
                conversion is rejected with ``ValueError`` because the current
                ``coords()`` / ``to_XYZ_block()`` path only returns coordinates
                for real atoms and cannot be aligned back to the original atom
                list safely.
            - ``"internal"``: require the molecule block to be rendered in
              internal-coordinate form.
              - If all atoms in a fragment already store internal coordinates,
                they are rendered directly in their current order.
              - If a fragment stores Cartesian coordinates, the fragment is
                converted with ``InternalCoords.from_cartesian_coords()`` and
                then reconstructed as Gaussian Z-matrix-style atom lines.
              - If the fragment contains dummy atoms or ghost atoms, the
                conversion is rejected with ``ValueError`` because the current
                Cartesian -> internal conversion path operates on the real-atom
                symbol/coordinate sequence returned by ``self.symbols()`` and
                ``self.coords()``, so it cannot be mapped back to the original
                mixed atom list safely.

            In other words, ``coords_type`` is now an active rendering control,
            but its supported scope is intentionally limited:
            - internal -> Cartesian is supported;
            - Cartesian -> internal is supported for ordinary real-atom
              fragments;
            - fragments containing dummy or ghost atoms are not converted
              implicitly in either direction.

        add_gjf_connectivity : bool, default False
            Whether to append a Gaussian connectivity section after the molecule
            coordinate block.

            Actual behavior:
            - ``False``: render only charge/multiplicity plus coordinates;
            - ``True``: append the connectivity information generated by
              ``self.connectivity()``.

        **kwargs
            Extra keyword arguments forwarded to downstream section, fragment,
            and atom ``_render()`` methods. This method consumes only a small
            subset directly; the rest are interpreted by child renderers if they
            recognize them.

        Returns
        -------
        str
            Complete Gaussian input text. The returned string always ends with
            two trailing newlines.

        Notes
        -----
        - This is a render-time override interface: supplied arguments affect
          only the current output and are not meant to be permanent field
          updates.
        - ``chk`` / ``old_chk`` append keywords to the ``link0_commands_to_use``
          object used for this render. If that object is ``self.link0_commands``,
          the appended entries may therefore be visible on the instance-backed
          object as a side effect.

        Returns
        -------
        str
            Rendered text for the selected frame.

        Source
        ------
        src/molop/io/logic/qminput_frame_models/GJFFileFrame.py:1401
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["orcainp"],
        file_path: os.PathLike | str | None = None,
        *,
        graph_policy: GraphPolicy = "prefer",
        keywords: str | None = ...,
        resources_raw: str | None = ...,
        nprocs: int | None = ...,
        maxcore: int | None = ...,
        blocks: str | None = ...,
        use_raw_geometry: bool = ...,
        **kwargs: Any,
    ) -> str:
        """Transform using the `orcainp` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        file_path :
            Optional output path. If provided, the rendered text is also written to a format-derived file.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the selected structure as an ORCA input deck.

        Format-specific parameters
        --------------------------
            keywords : str | None
                Format-specific writer argument (optional).
            resources_raw : str | None
                Format-specific writer argument (optional).
            nprocs : int | None
                Format-specific writer argument (optional).
            maxcore : int | None
                Format-specific writer argument (optional).
            blocks : str | None
                Format-specific writer argument (optional).
            use_raw_geometry : bool
                Format-specific writer argument (optional).

        Render the selected structure as an ORCA input deck.

        Returns
        -------
        str
            Rendered text for the selected frame.

        Source
        ------
        src/molop/io/logic/qminput_frame_models/ORCAInpFileFrame.py:25
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["sdf"],
        file_path: os.PathLike | str | None = None,
        *,
        graph_policy: GraphPolicy = "prefer",
        engine: Literal["rdkit", "openbabel"] = ...,
        **kwargs: Any,
    ) -> str:
        """Transform using the `sdf` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        file_path :
            Optional output path. If provided, the rendered text is also written to a format-derived file.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the SDFFileFrame as a string.

        Format-specific parameters
        --------------------------
            engine : Literal['rdkit', 'openbabel']
                Format-specific writer argument (optional).

        Render the SDFFileFrame as a string.

        Args:
            engine (Literal["rdkit", "openbabel"], optional): The engine to use for rendering. Defaults to "rdkit".

        Returns:
            str: The rendered SDFFileFrame.

        Returns
        -------
        str
            Rendered text for the selected frame.

        Source
        ------
        src/molop/io/logic/coords_frame_models/SDFFileFrame.py:18
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["smi"],
        file_path: os.PathLike | str | None = None,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> str:
        """Transform using the `smi` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        file_path :
            Optional output path. If provided, the rendered text is also written to a format-derived file.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the selected structure as a SMILES string.

        Format-specific parameters
        --------------------------
            None.

        Render the selected structure as a SMILES string.

        Returns
        -------
        str
            Rendered text for the selected frame.

        Source
        ------
        src/molop/io/logic/coords_frame_models/SMIFileFrame.py:16
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["xyz"],
        file_path: os.PathLike | str | None = None,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> str:
        """Transform using the `xyz` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        file_path :
            Optional output path. If provided, the rendered text is also written to a format-derived file.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the XYZ file frame as a string.

        Format-specific parameters
        --------------------------
            None.

        Render the XYZ file frame as a string.

        Returns:
            str: The rendered XYZ file frame.

        Returns
        -------
        str
            Rendered text for the selected frame.

        Source
        ------
        src/molop/io/logic/coords_frame_models/XYZFileFrame.py:20
        """
        ...
    @overload
    def format_transform(
        self,
        format: str,
        file_path: os.PathLike | str | None = None,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> str:
        """Transform using a format string and format-specific writer options.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        file_path :
            Optional output path. If provided, the rendered text is also written to a format-derived file.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior by format
        -------------------------
        cml :
            Render the selected structure as CML text.
        gjf :
            Render the current GJF frame as Gaussian input text.
        orcainp :
            Render the selected structure as an ORCA input deck.
        sdf :
            Render the SDFFileFrame as a string.
        smi :
            Render the selected structure as a SMILES string.
        xyz :
            Render the XYZ file frame as a string.

        Format-specific parameters by format
        ------------------------------------
        cml :
            engine : Literal['rdkit', 'openbabel']
                Format-specific writer argument (optional).
        gjf :
            link0_commands : str | GJFLink0Commands | dict[str, str | None] | None
                Format-specific writer argument (optional).
            route_section : str | GJFRouteSection | None
                Format-specific writer argument (optional).
            title_card : str | GJFTitleCard | None
                Format-specific writer argument (optional).
            molecule_specifications : str | GJFMoleculeSpecifications | None
                Format-specific writer argument (optional).
            additional_sections : str | None
                Format-specific writer argument (optional).
            parsed_additional_sections : list[GJFGICSection | GJFModRedundantSection | GJFUnknownSection] | None
                Format-specific writer argument (optional).
            chk : str | bool | None
                Format-specific writer argument (optional).
            old_chk : bool | str | None
                Format-specific writer argument (optional).
            coords_type : Literal['cartesian', 'internal', 'auto']
                Format-specific writer argument (optional).
            add_gjf_connectivity : bool
                Format-specific writer argument (optional).
        orcainp :
            keywords : str | None
                Format-specific writer argument (optional).
            resources_raw : str | None
                Format-specific writer argument (optional).
            nprocs : int | None
                Format-specific writer argument (optional).
            maxcore : int | None
                Format-specific writer argument (optional).
            blocks : str | None
                Format-specific writer argument (optional).
            use_raw_geometry : bool
                Format-specific writer argument (optional).
        sdf :
            engine : Literal['rdkit', 'openbabel']
                Format-specific writer argument (optional).
        smi :
            None.
        xyz :
            None.

        Returns
        -------
        str
            Rendered text for the selected frame.

        Source
        ------
        cml : src/molop/io/codecs/cml_codec.py:78
        gjf : src/molop/io/logic/qminput_frame_models/GJFFileFrame.py:1401
        orcainp : src/molop/io/logic/qminput_frame_models/ORCAInpFileFrame.py:25
        sdf : src/molop/io/logic/coords_frame_models/SDFFileFrame.py:18
        smi : src/molop/io/logic/coords_frame_models/SMIFileFrame.py:16
        xyz : src/molop/io/logic/coords_frame_models/XYZFileFrame.py:20
        """
        ...

class FormatTransformMixin:
    @overload
    def format_transform(
        self,
        format: Literal["cml"],
        frameID: Sequence[int] | int | Literal["all"] | slice = -1,
        file_path: os.PathLike | str | None = None,
        embed_in_one_file: bool = True,
        *,
        graph_policy: GraphPolicy = "prefer",
        engine: Literal["rdkit", "openbabel"] = ...,
        **kwargs: Any,
    ) -> str | list[str]:
        """Transform using the `cml` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        frameID :
            Frame selector forwarded to rendering; accepts index, sequence, slice, or `"all"`.
        file_path :
            Optional output path. If omitted, a format-derived path is used.
        embed_in_one_file :
            Whether selected frames are embedded into one file when supported by the format.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the selected structure as CML text.

        Format-specific parameters
        --------------------------
            engine : Literal['rdkit', 'openbabel']
                Format-specific writer argument (optional).

        Render the selected structure as CML text.

        Returns
        -------
        str | list[str]
            Rendered text for the selected frame set as a single string or a list of per-frame strings.

        Source
        ------
        src/molop/io/codecs/cml_codec.py:47
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["gjf"],
        frameID: Sequence[int] | int | Literal["all"] | slice = -1,
        file_path: os.PathLike | str | None = None,
        embed_in_one_file: bool = True,
        *,
        graph_policy: GraphPolicy = "prefer",
        link0_commands: str | GJFLink0Commands | dict[str, str | None] | None = ...,
        route_section: str | GJFRouteSection | None = ...,
        title_card: str | GJFTitleCard | None = ...,
        molecule_specifications: str | GJFMoleculeSpecifications | None = ...,
        additional_sections: str | None = ...,
        parsed_additional_sections: list[GJFGICSection | GJFModRedundantSection | GJFUnknownSection]
        | None = ...,
        chk: str | bool | None = ...,
        old_chk: bool | str | None = ...,
        coords_type: Literal["cartesian", "internal", "auto"] = ...,
        add_gjf_connectivity: bool = ...,
        **kwargs: Any,
    ) -> str | list[str]:
        """Transform using the `gjf` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        frameID :
            Frame selector forwarded to rendering; accepts index, sequence, slice, or `"all"`.
        file_path :
            Optional output path. If omitted, a format-derived path is used.
        embed_in_one_file :
            Whether selected frames are embedded into one file when supported by the format.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the current GJF frame as Gaussian input text.

        Format-specific parameters
        --------------------------
            link0_commands : str | GJFLink0Commands | dict[str, str | None] | None
                Format-specific writer argument (optional).
            route_section : str | GJFRouteSection | None
                Format-specific writer argument (optional).
            title_card : str | GJFTitleCard | None
                Format-specific writer argument (optional).
            molecule_specifications : str | GJFMoleculeSpecifications | None
                Format-specific writer argument (optional).
            additional_sections : str | None
                Format-specific writer argument (optional).
            parsed_additional_sections : list[GJFGICSection | GJFModRedundantSection | GJFUnknownSection] | None
                Format-specific writer argument (optional).
            chk : str | bool | None
                Format-specific writer argument (optional).
            old_chk : bool | str | None
                Format-specific writer argument (optional).
            coords_type : Literal['cartesian', 'internal', 'auto']
                Format-specific writer argument (optional).
            add_gjf_connectivity : bool
                Format-specific writer argument (optional).

        Render the current GJF frame as Gaussian input text.

        The method assembles the output in standard Gaussian input order:
        1. Link0 commands
        2. Route section
        3. Title card
        4. Molecule specifications
        5. Additional sections

        Callers may temporarily override any of these parts for a single render
        without mutating the instance first. Any argument left as ``None`` falls
        back to the corresponding attribute on ``self``.

        Parameters
        ----------
        link0_commands : str | GJFLink0Commands | dict[str, str | None] | None, optional
            Link0 content, i.e. the resource and job-control directives at the
            beginning of the file such as ``%mem``, ``%nprocshared``, and
            ``%chk``.

            Actual behavior:
            - ``str``: parsed as Link0 syntax into ``GJFLink0Commands``;
            - ``dict``: converted into a Link0 keyword list;
            - ``GJFLink0Commands``: used directly;
            - ``None``: falls back to ``self.link0_commands``.

        route_section : str | GJFRouteSection | None, optional
            Gaussian route section, i.e. the keyword line beginning with ``#``,
            for example ``#p b3lyp/6-31g(d) opt freq``.

            Actual behavior:
            - ``str``: converted to ``GJFRouteSection`` and normalized there;
            - ``GJFRouteSection``: used directly;
            - ``None``: falls back to ``self.route_section``.

        title_card : str | GJFTitleCard | None, optional
            Gaussian title section.

            Actual behavior:
            - ``str``: converted to ``GJFTitleCard``;
            - ``GJFTitleCard``: used directly;
            - ``None``: falls back to ``self.title_card``;
            - if the final title is empty, it falls back to ``self.pure_filename``
              or, if unavailable, ``"title"``.

        molecule_specifications : str | GJFMoleculeSpecifications | None, optional
            Molecule specification block, i.e. the charge/multiplicity line plus
            the coordinate block that follows it.

            Actual behavior:
            - ``str``: parsed as Gaussian molecule-block syntax into
              ``GJFMoleculeSpecifications``;
            - ``GJFMoleculeSpecifications``: used directly;
            - ``None``: falls back to ``self.molecule_specifications``.

        additional_sections : str | None, optional
            Raw additional-section text appended after the main molecule block,
            such as GIC, ModRedundant, NBO, or other Gaussian extra-input blocks.

            Actual behavior:
            - whenever this argument is explicitly provided, it has top priority;
            - even an empty string overrides the structured additional-section
              sources.

        parsed_additional_sections : list[...] | None, optional
            Structured additional sections. Each section is rendered via its own
            ``_render()`` and then joined with blank lines.

            Actual behavior:
            - only used when ``additional_sections is None``;
            - when provided, it takes priority over
              ``self.parsed_additional_sections``;
            - sections whose rendered text is blank are skipped.

            Additional-section priority is:
            1. ``additional_sections``
            2. ``parsed_additional_sections``
            3. ``self.parsed_additional_sections``
            4. ``self.additional_sections``
            5. empty string

        chk : str | bool | None, optional
            Whether to append an extra ``%chk`` Link0 keyword for this render.

            Actual behavior:
            - ``None`` / ``False``: do not append anything;
            - ``True``: append ``%chk=<basename>.chk``;
            - ``str``: append ``%chk=<given string>``.

            ``<basename>`` is taken from ``self.pure_filename`` when available,
            otherwise from the final title card. This is an append operation, not
            a replacement, and existing ``%chk`` entries are not deduplicated.

        old_chk : str | bool | None, optional
            Whether to append an extra ``%oldchk`` Link0 keyword for this render,
            typically to reference a previous checkpoint file.

            Actual behavior matches ``chk``:
            - ``None`` / ``False``: do not append anything;
            - ``True``: append ``%oldchk=<basename>.chk``;
            - ``str``: append ``%oldchk=<given string>``.

            This is also an append operation and does not replace or deduplicate
            existing ``%oldchk`` entries.

        coords_type : {"cartesian", "internal", "auto"}, default "auto"
            Controls the preferred output form of the coordinate block.

            Actual behavior in the current implementation:
            - ``"auto"``: preserve the stored representation. Each atom
              specification renders itself according to the structure of its own
              ``coords_part``: Cartesian coordinates, internal coordinates, or
              raw text.
            - ``"cartesian"``: require the molecule block to be rendered in
              Cartesian coordinates.
              - If all atoms in a fragment already store Cartesian coordinates,
                they are rendered directly in their current order.
              - If a fragment stores internal coordinates, the fragment is first
                converted through ``frag.coords()`` and then reconstructed as
                Cartesian atom lines.
              - If the fragment contains dummy atoms or ghost atoms, the
                conversion is rejected with ``ValueError`` because the current
                ``coords()`` / ``to_XYZ_block()`` path only returns coordinates
                for real atoms and cannot be aligned back to the original atom
                list safely.
            - ``"internal"``: require the molecule block to be rendered in
              internal-coordinate form.
              - If all atoms in a fragment already store internal coordinates,
                they are rendered directly in their current order.
              - If a fragment stores Cartesian coordinates, the fragment is
                converted with ``InternalCoords.from_cartesian_coords()`` and
                then reconstructed as Gaussian Z-matrix-style atom lines.
              - If the fragment contains dummy atoms or ghost atoms, the
                conversion is rejected with ``ValueError`` because the current
                Cartesian -> internal conversion path operates on the real-atom
                symbol/coordinate sequence returned by ``self.symbols()`` and
                ``self.coords()``, so it cannot be mapped back to the original
                mixed atom list safely.

            In other words, ``coords_type`` is now an active rendering control,
            but its supported scope is intentionally limited:
            - internal -> Cartesian is supported;
            - Cartesian -> internal is supported for ordinary real-atom
              fragments;
            - fragments containing dummy or ghost atoms are not converted
              implicitly in either direction.

        add_gjf_connectivity : bool, default False
            Whether to append a Gaussian connectivity section after the molecule
            coordinate block.

            Actual behavior:
            - ``False``: render only charge/multiplicity plus coordinates;
            - ``True``: append the connectivity information generated by
              ``self.connectivity()``.

        **kwargs
            Extra keyword arguments forwarded to downstream section, fragment,
            and atom ``_render()`` methods. This method consumes only a small
            subset directly; the rest are interpreted by child renderers if they
            recognize them.

        Returns
        -------
        str
            Complete Gaussian input text. The returned string always ends with
            two trailing newlines.

        Notes
        -----
        - This is a render-time override interface: supplied arguments affect
          only the current output and are not meant to be permanent field
          updates.
        - ``chk`` / ``old_chk`` append keywords to the ``link0_commands_to_use``
          object used for this render. If that object is ``self.link0_commands``,
          the appended entries may therefore be visible on the instance-backed
          object as a side effect.

        Returns
        -------
        str | list[str]
            Rendered text for the selected frame set as a single string or a list of per-frame strings.

        Source
        ------
        src/molop/io/logic/qminput_frame_models/GJFFileFrame.py:1401
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["orcainp"],
        frameID: Sequence[int] | int | Literal["all"] | slice = -1,
        file_path: os.PathLike | str | None = None,
        embed_in_one_file: bool = True,
        *,
        graph_policy: GraphPolicy = "prefer",
        keywords: str | None = ...,
        resources_raw: str | None = ...,
        nprocs: int | None = ...,
        maxcore: int | None = ...,
        blocks: str | None = ...,
        use_raw_geometry: bool = ...,
        **kwargs: Any,
    ) -> str | list[str]:
        """Transform using the `orcainp` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        frameID :
            Frame selector forwarded to rendering; accepts index, sequence, slice, or `"all"`.
        file_path :
            Optional output path. If omitted, a format-derived path is used.
        embed_in_one_file :
            Whether selected frames are embedded into one file when supported by the format.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the selected structure as an ORCA input deck.

        Format-specific parameters
        --------------------------
            keywords : str | None
                Format-specific writer argument (optional).
            resources_raw : str | None
                Format-specific writer argument (optional).
            nprocs : int | None
                Format-specific writer argument (optional).
            maxcore : int | None
                Format-specific writer argument (optional).
            blocks : str | None
                Format-specific writer argument (optional).
            use_raw_geometry : bool
                Format-specific writer argument (optional).

        Render the selected structure as an ORCA input deck.

        Returns
        -------
        str | list[str]
            Rendered text for the selected frame set as a single string or a list of per-frame strings.

        Source
        ------
        src/molop/io/logic/qminput_frame_models/ORCAInpFileFrame.py:25
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["sdf"],
        frameID: Sequence[int] | int | Literal["all"] | slice = -1,
        file_path: os.PathLike | str | None = None,
        embed_in_one_file: bool = True,
        *,
        graph_policy: GraphPolicy = "prefer",
        engine: Literal["rdkit", "openbabel"] = ...,
        **kwargs: Any,
    ) -> str | list[str]:
        """Transform using the `sdf` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        frameID :
            Frame selector forwarded to rendering; accepts index, sequence, slice, or `"all"`.
        file_path :
            Optional output path. If omitted, a format-derived path is used.
        embed_in_one_file :
            Whether selected frames are embedded into one file when supported by the format.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the SDFFileFrame as a string.

        Format-specific parameters
        --------------------------
            engine : Literal['rdkit', 'openbabel']
                Format-specific writer argument (optional).

        Render the SDFFileFrame as a string.

        Args:
            engine (Literal["rdkit", "openbabel"], optional): The engine to use for rendering. Defaults to "rdkit".

        Returns:
            str: The rendered SDFFileFrame.

        Returns
        -------
        str | list[str]
            Rendered text for the selected frame set as a single string or a list of per-frame strings.

        Source
        ------
        src/molop/io/logic/coords_frame_models/SDFFileFrame.py:18
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["smi"],
        frameID: Sequence[int] | int | Literal["all"] | slice = -1,
        file_path: os.PathLike | str | None = None,
        embed_in_one_file: bool = True,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> str | list[str]:
        """Transform using the `smi` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        frameID :
            Frame selector forwarded to rendering; accepts index, sequence, slice, or `"all"`.
        file_path :
            Optional output path. If omitted, a format-derived path is used.
        embed_in_one_file :
            Whether selected frames are embedded into one file when supported by the format.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the selected structure as a SMILES string.

        Format-specific parameters
        --------------------------
            None.

        Render the selected structure as a SMILES string.

        Returns
        -------
        str | list[str]
            Rendered text for the selected frame set as a single string or a list of per-frame strings.

        Source
        ------
        src/molop/io/logic/coords_frame_models/SMIFileFrame.py:16
        """
        ...
    @overload
    def format_transform(
        self,
        format: Literal["xyz"],
        frameID: Sequence[int] | int | Literal["all"] | slice = -1,
        file_path: os.PathLike | str | None = None,
        embed_in_one_file: bool = True,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> str | list[str]:
        """Transform using the `xyz` writer overload.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        frameID :
            Frame selector forwarded to rendering; accepts index, sequence, slice, or `"all"`.
        file_path :
            Optional output path. If omitted, a format-derived path is used.
        embed_in_one_file :
            Whether selected frames are embedded into one file when supported by the format.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior
        ---------------
            Render the XYZ file frame as a string.

        Format-specific parameters
        --------------------------
            None.

        Render the XYZ file frame as a string.

        Returns:
            str: The rendered XYZ file frame.

        Returns
        -------
        str | list[str]
            Rendered text for the selected frame set as a single string or a list of per-frame strings.

        Source
        ------
        src/molop/io/logic/coords_frame_models/XYZFileFrame.py:20
        """
        ...
    @overload
    def format_transform(
        self,
        format: str,
        frameID: Sequence[int] | int | Literal["all"] | slice = -1,
        file_path: os.PathLike | str | None = None,
        embed_in_one_file: bool = True,
        *,
        graph_policy: GraphPolicy = "prefer",
        **kwargs: Any,
    ) -> str | list[str]:
        """Transform using a format string and format-specific writer options.

        Parameters
        ----------
        format :
            Target output format literal for this overload.
        frameID :
            Frame selector forwarded to rendering; accepts index, sequence, slice, or `"all"`.
        file_path :
            Optional output path. If omitted, a format-derived path is used.
        embed_in_one_file :
            Whether selected frames are embedded into one file when supported by the format.
        graph_policy :
            Molecular graph policy used before rendering (for example, `"prefer"`).
        **kwargs :
            Additional writer options accepted by the implementation.

        Format behavior by format
        -------------------------
        cml :
            Render the selected structure as CML text.
        gjf :
            Render the current GJF frame as Gaussian input text.
        orcainp :
            Render the selected structure as an ORCA input deck.
        sdf :
            Render the SDFFileFrame as a string.
        smi :
            Render the selected structure as a SMILES string.
        xyz :
            Render the XYZ file frame as a string.

        Format-specific parameters by format
        ------------------------------------
        cml :
            engine : Literal['rdkit', 'openbabel']
                Format-specific writer argument (optional).
        gjf :
            link0_commands : str | GJFLink0Commands | dict[str, str | None] | None
                Format-specific writer argument (optional).
            route_section : str | GJFRouteSection | None
                Format-specific writer argument (optional).
            title_card : str | GJFTitleCard | None
                Format-specific writer argument (optional).
            molecule_specifications : str | GJFMoleculeSpecifications | None
                Format-specific writer argument (optional).
            additional_sections : str | None
                Format-specific writer argument (optional).
            parsed_additional_sections : list[GJFGICSection | GJFModRedundantSection | GJFUnknownSection] | None
                Format-specific writer argument (optional).
            chk : str | bool | None
                Format-specific writer argument (optional).
            old_chk : bool | str | None
                Format-specific writer argument (optional).
            coords_type : Literal['cartesian', 'internal', 'auto']
                Format-specific writer argument (optional).
            add_gjf_connectivity : bool
                Format-specific writer argument (optional).
        orcainp :
            keywords : str | None
                Format-specific writer argument (optional).
            resources_raw : str | None
                Format-specific writer argument (optional).
            nprocs : int | None
                Format-specific writer argument (optional).
            maxcore : int | None
                Format-specific writer argument (optional).
            blocks : str | None
                Format-specific writer argument (optional).
            use_raw_geometry : bool
                Format-specific writer argument (optional).
        sdf :
            engine : Literal['rdkit', 'openbabel']
                Format-specific writer argument (optional).
        smi :
            None.
        xyz :
            None.

        Returns
        -------
        str | list[str]
            Rendered text for the selected frame set as a single string or a list of per-frame strings.

        Source
        ------
        cml : src/molop/io/codecs/cml_codec.py:47
        gjf : src/molop/io/logic/qminput_frame_models/GJFFileFrame.py:1401
        orcainp : src/molop/io/logic/qminput_frame_models/ORCAInpFileFrame.py:25
        sdf : src/molop/io/logic/coords_frame_models/SDFFileFrame.py:18
        smi : src/molop/io/logic/coords_frame_models/SMIFileFrame.py:16
        xyz : src/molop/io/logic/coords_frame_models/XYZFileFrame.py:20
        """
        ...
